### PR TITLE
fix encapsed string conversion

### LINKED ISSUE #20: Add support for String Interpolation when migrating helper methods
Right now we have a test which fails because we are trying to migrate a class method to a pest helper method. 

However the original class method was used in string interpolation which is not supported by functions, so the string interpolation has to be split up, so it can use the pest helper.

Example:
We have the following php class
```php
class MethodStringInterpolationTest extends TestCase
{
    private function alwaysTrueHelper()
    {
        return "true";
    }

    public function testMethod()
    {
        "{$this->alwaysTrueHelper()} works";
    }
}
```
Which should be converted to 
```
function alwaysTrueHelper()
{
    return "true";
}
test('testMethod', function () {
    alwaysTrueHelper() . " works";
});
```

Because doing ` "{alwaysTrueHelper()} works";` is not valid php code.

Fixture file:
https://github.com/pestphp/drift/blob/master/tests/fixtures/PHPUnit/ClassMethod/HelperMethodRector/phpunit_method_to_pest_helper_used_in_string_interpolation.php.inc

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #20 

---

Failing CI is unrelated, looks like unfinished `RemovePHPUnitClassRectorTest`

---

This error:

```bash
Error: Call to a member function dumpFile() on null
```

will be fixed in #23

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Btw, I didn't found any ECS or any other coding standards. So my code looks like crap :D

Shall I add it?

**Comment by owenvoke** [comment]
It's probably worth us adding the `pestphp/pest-dev-tools` package for consistency with our other repos. :thinking: :+1:

**Comment by olivernybroe** [comment]
@TomasVotruba Thanks a lot for Rector, it's really an amazing tool 👍 

It made it so easy for us to make this project.

File: src/PHPUnit/ClassMethod/HelperMethodRector.php [hunk 1]
```diff
@@ -111,18 +112,31 @@ private function migratePhpUnitMethodHelpers(Node $pestNode, ClassMethod $method
...
+//            // probably your case to skip
+//            // https://github.com/rectorphp/rector/blob/master/docs/nodes_overview.md#phpparsernodescalarencapsed
+//            if ($parentNode instanceof Encapsed) {
+//                foreach ($parentNode->parts as $encapsedPart) {
+//                    $this->addNodeAfterNode($encapsedPart, $node);
+//                }
+//
+//                return null;
+//            }
+
```
Comment (TomasVotruba) [inline src/PHPUnit/ClassMethod/HelperMethodRector.php:139]: Ups. Coding standard usually catches these.

It should be he handled by ECS PR

Comment (olivernybroe) [reply src/PHPUnit/ClassMethod/HelperMethodRector.php:139]: Yeah, saw that, but didn't wanna comment on it, because of the ECS PR 👍

**Comment by TomasVotruba** [comment]
You're welcome. I'm glad I can help devs to be lazy and enjoy their work more :)

After the ECS gets merged, I'll look on Rector setup here. One step at a time

**Comment by olivernybroe** [comment]
@TomasVotruba Awesome! Thanks 👍 

Love being a lazy dev 😉
